name: ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:

  ubuntu-build:
    runs-on: ${{ matrix.ubuntu-distro }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-distro:
          - ubuntu-22.04

    steps:
      - name: Sync repository
        uses: actions/checkout@v4

      - name: Install apt packages
        run: |
              sudo apt update && sudo apt -y install \
              software-properties-common \
              qtbase6-dev \
              libqt6svg6-dev \
              libqt6websockets6-dev \
              libqt6opengl6-dev \
              libqt6x11extras6-dev \
              libprotoc-dev \
              libzmq3-dev \
              liblz4-dev \
              libzstd-dev \
              ccache

      - name: Prepare ccache
        shell: bash
        run: |
          mkdir -p ${{ runner.temp }}/ccache/tmp

      - name: Save ccache folder
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/ccache
          key: ${{ runner.os }}-${{ matrix.ubuntu-distro }}

      - name: Build Plotjuggler
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CCACHE_DIR: ${{ runner.temp }}/ccache
        run: |
            cmake . -B build -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            cmake --build build

      - name: Build AppImage
        working-directory: ${{ github.workspace }}
        if: github.event_name == 'release'
        run: |
            wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
            wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
            chmod +x linuxdeploy*.AppImage
            mkdir -p AppDir/usr/bin
            cp -v build/bin/* AppDir/usr/bin
            ./linuxdeploy-x86_64.AppImage --appdir=AppDir \
              -d ./PlotJuggler.desktop \
              -i ./plotjuggler.png \
              --plugin qt --output appimage

      - name: Upload AppImage
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: PlotJuggler-x86_64.AppImage
